export const appVersion = '1.0.0';
export const buildYear = 2026;

export type AboutLegalBlock =
  | { type: 'eyebrow'; text: string }
  | { type: 'lead'; text: string }
  | { type: 'heading'; text: string }
  | { type: 'paragraph'; text: string };

export const aboutLegalContent: Record<string, AboutLegalBlock[]> = {
  pt: [
    { type: 'eyebrow', text: 'Versão 1.0.0' },
    { type: 'lead', text: 'Um sistema de gestão de bibliotecas pessoais e promoção da leitura.' },
    { type: 'heading', text: 'Sobre' },
    { type: 'paragraph', text: 'Folium é a versão educacional de Biblioteca, um projeto da Kendir Studios (Worlds4Education – Jogos e Ambientes Educativos, Lda.), construído do nosso amor por livros e pelo prazer de construir a nossa pequena biblioteca, um livro de cada vez. Somos enormes fãs de leitura e acreditamos que os livros nos dão algo que não encontramos em mais nenhum lugar. Mas os hábitos de leitura estão a desaparecer, lentamente, dos nossos jovens e alunos.' },
    { type: 'paragraph', text: 'Procuramos ajudar através de Folium, permitindo aos alunos descobrir livros, explorar planos de leitura, encontrar bibliotecas, partilhar livros e leituras com colegas e fazer evoluir uma biblioteca pessoal que possa ser um local de refúgio e crescimento durante os anos formativos.' },
    { type: 'heading', text: 'A nossa intenção' },
    { type: 'paragraph', text: 'A nossa intenção é simples: dar aos alunos um local onde possam catalogar os seus livros, partilhá-los com amigos e colegas e descobrir novas leituras. Sem algoritmos, publicidade ou ruído – apenas o aluno e as suas folhas!' },
    { type: 'heading', text: 'Termos e Condições' },
    { type: 'paragraph', text: 'Última atualização: 20 Abril 2026' },
    { type: 'paragraph', text: 'Ao usar Folium, está a acordar aos Termos e Condições.' },
    { type: 'paragraph', text: 'O uso de Folium para qualquer uso para além da gestão de bibliotecas pessoais por estudantes não é permitido.' },
    { type: 'paragraph', text: 'A disponibilidade do serviço do Folium pode ser interrompida ou modificada, incluindo alguma das suas funcionalidades. Se tala acontecer, iremos informar com a devida antecedência.' },
    { type: 'paragraph', text: 'Os dados e imagens das capas são obtidos através de APIs (Open Library, Google Books) e estão sujeitos aos termos e condições desses serviços.' },
    { type: 'paragraph', text: 'Atualizações aos termos e condições podem ser efetuadas ocasionalmente.' },
    { type: 'paragraph', text: 'Worlds4Education – Jogos e Ambientes Educativos, Lda.' },
    { type: 'paragraph', text: 'Avenida da República 1629 – 2.º Esquerdo' },
    { type: 'paragraph', text: '4430-206 Vila Nova de Gaia - Portugal' },
  ],
  en: [
    { type: 'eyebrow', text: 'Version 1.0.0' },
    { type: 'lead', text: 'A system for managing personal libraries and promoting reading.' },
    { type: 'heading', text: 'About' },
    { type: 'paragraph', text: "Folium is the educational version of Biblioteca, a project by Kendir Studios (Worlds4Education – Jogos e Ambientes Educativos, Lda.), built from our love for books and the pleasure of building our small library, one book at a time. We're huge fans of reading, and we believe that books give us something we can't find anywhere else. But reading habits are slowly disappearing from our young people and students." },
    { type: 'paragraph', text: 'We seek to help through Folium, allowing students to discover books, explore reading plans, find libraries, share books and readings with peers, and evolve a personal library that can be a place of refuge and growth during the formative years.' },
    { type: 'heading', text: 'Our intention' },
    { type: 'paragraph', text: 'Our intention is simple: to give students a place where they can catalogue their books, share them with friends and colleagues and discover new readings. No algorithms, advertising or noise – just the student and their sheets!' },
    { type: 'heading', text: 'Terms and Conditions' },
    { type: 'paragraph', text: 'Last updated: 20 April 2026' },
    { type: 'paragraph', text: 'By using Folium, you agree to the Terms and Conditions.' },
    { type: 'paragraph', text: 'The use of Folium for any use other than the management of personal libraries by students is not permitted.' },
    { type: 'paragraph', text: 'The availability of the Folium service may be interrupted or modified, including some of its features. If this happens, we will inform you in advance.' },
    { type: 'paragraph', text: 'The data and images of the covers are obtained through APIs (Open Library, Google Books) and are subject to the terms and conditions of these services.' },
    { type: 'paragraph', text: 'Updates to the terms and conditions may be made from time to time.' },
    { type: 'paragraph', text: 'Worlds4Education – Jogos e Ambientes Educativos, Lda.' },
    { type: 'paragraph', text: 'Avenida da República 1629 – 2nd Left' },
    { type: 'paragraph', text: '4430-206 Vila Nova de Gaia - Portugal' },
  ],
  es: [
    { type: 'eyebrow', text: 'Versión 1.0.0' },
    { type: 'lead', text: 'Un sistema para gestionar bibliotecas personales y promover la lectura.' },
    { type: 'heading', text: 'Acerca de' },
    { type: 'paragraph', text: 'Folium es la versión educativa de Biblioteca, un proyecto de Kendir Studios (Worlds4Education – Jogos e Ambientes Educativos, Lda.), construido a partir de nuestro amor por los libros y el placer de construir nuestra pequeña biblioteca, libro a libro. Somos grandes aficionados a la lectura y creemos que los libros nos ofrecen algo que no encontramos en ningún otro sitio. Pero los hábitos de lectura están desapareciendo poco a poco de nuestros jóvenes y estudiantes.' },
    { type: 'paragraph', text: 'Buscamos ayudar a través de Folium, permitiendo a los estudiantes descubrir libros, explorar planes de lectura, encontrar bibliotecas, compartir libros y lecturas con sus compañeros, y desarrollar una biblioteca personal que pueda ser un lugar de refugio y crecimiento durante los años formativos.' },
    { type: 'heading', text: 'Nuestra intención' },
    { type: 'paragraph', text: 'Nuestra intención es sencilla: ofrecer a los estudiantes un lugar donde puedan catalogar sus libros, compartirlos con amigos y compañeros y descubrir nuevas lecturas. Sin algoritmos, publicidad ni ruido, ¡solo el estudiante y sus sábanas!' },
    { type: 'heading', text: 'Términos y Condiciones' },
    { type: 'paragraph', text: 'Última actualización: 20 de abril de 2026' },
    { type: 'paragraph', text: 'Al utilizar Folium, aceptas los Términos y Condiciones.' },
    { type: 'paragraph', text: 'No se permite el uso de Folium para cualquier uso distinto a la gestión de bibliotecas personales por parte de los estudiantes.' },
    { type: 'paragraph', text: 'La disponibilidad del servicio Folium puede verse interrumpida o modificada, incluyendo algunas de sus características. Si esto ocurre, te informaremos con antelación.' },
    { type: 'paragraph', text: 'Los datos e imágenes de las portadas se obtienen a través de APIs (Open Library, Google Books) y están sujetos a los términos y condiciones de estos servicios.' },
    { type: 'paragraph', text: 'Se pueden hacer actualizaciones de los términos y condiciones de vez en cuando.' },
    { type: 'paragraph', text: 'Worlds4Education – Jogos e Ambientes Educativos, Lda.' },
    { type: 'paragraph', text: 'Avenida da República 1629 – 2ª izquierda' },
    { type: 'paragraph', text: '4430-206 Vila Nova de Gaia - Portugal' },
  ],
  fr: [
    { type: 'eyebrow', text: 'Version 1.0.0' },
    { type: 'lead', text: 'Un système pour gérer les bibliothèques personnelles et promouvoir la lecture.' },
    { type: 'heading', text: 'À propos' },
    { type: 'paragraph', text: "Folium est la version éducative de Biblioteca, un projet de Kendir Studios (Worlds4Education – Jogos e Ambientes Educativos, Lda.), né de notre amour des livres et du plaisir de construire notre petite bibliothèque, un livre à la fois. Nous sommes de grands amateurs de lecture, et nous croyons que les livres nous offrent quelque chose que nous ne trouvons nulle part ailleurs. Mais les habitudes de lecture disparaissent lentement chez nos jeunes et nos élèves." },
    { type: 'paragraph', text: "Nous cherchons à aider via Folium, permettant aux élèves de découvrir des livres, d'explorer des plans de lecture, de trouver des bibliothèques, de partager des livres et des lectures avec leurs pairs, et de développer une bibliothèque personnelle pouvant être un lieu de refuge et de croissance durant les années formatrices." },
    { type: 'heading', text: 'Notre intention' },
    { type: 'paragraph', text: "Notre intention est simple : offrir aux élèves un espace où ils peuvent cataloguer leurs livres, les partager avec des amis et des collègues et découvrir de nouvelles lectures. Pas d'algorithmes, de publicité ni de bruit – juste l'étudiant et ses feuilles !" },
    { type: 'heading', text: 'Conditions Générales' },
    { type: 'paragraph', text: 'Dernière mise à jour : 20 avril 2026' },
    { type: 'paragraph', text: 'En utilisant Folium, vous acceptez les Conditions générales.' },
    { type: 'paragraph', text: "L'utilisation de Folium pour tout usage autre que la gestion de bibliothèques personnelles par les étudiants n'est pas autorisée." },
    { type: 'paragraph', text: "La disponibilité du service Folium peut être interrompue ou modifiée, y compris certaines de ses fonctionnalités. Si cela arrive, nous vous informerons à l'avance." },
    { type: 'paragraph', text: 'Les données et images des couvertures sont obtenues via des API (Open Library, Google Books) et sont soumises aux termes et conditions de ces services.' },
    { type: 'paragraph', text: 'Des mises à jour des termes et conditions peuvent être effectuées de temps à autre.' },
    { type: 'paragraph', text: 'Worlds4Education – Jogos e Ambientes Educativos, Lda.' },
    { type: 'paragraph', text: 'Avenida da República 1629 – 2e à gauche' },
    { type: 'paragraph', text: '4430-206 Vila Nova de Gaia - Portugal' },
  ],
};
