ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS tutorial_completed boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS tutorial_step integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS tutorial_started_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS tutorial_chapter_statuses jsonb NOT NULL DEFAULT '["pending","pending","pending","pending","pending","pending","pending","pending","pending","pending"]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_profiles_tutorial_completed ON public.profiles (tutorial_completed);

INSERT INTO public.app_content (key, category, value_pt, value_en, value_fr, value_es)
VALUES
('tutorial.chapter_1.heading','tutorial','A tua biblioteca começa aqui.','Your library starts here.','Ta bibliothèque commence ici.','Tu biblioteca empieza aquí.'),
('tutorial.chapter_1.body','tutorial','O Folium é o teu espaço para guardar os livros que tens, os que queres ler, e os que já leste. Cada livro que adicionas é uma folha na tua árvore. Vamos começar por criar a tua primeira estante.','Folium is your space to keep the books you own, the ones you want to read, and the ones you have already read. Every book you add is a leaf on your tree. Let’s begin by creating your first shelf.','Folium est ton espace pour garder les livres que tu as, ceux que tu veux lire et ceux que tu as déjà lus. Chaque livre ajouté est une feuille sur ton arbre. Commençons par créer ta première étagère.','Folium es tu espacio para guardar los libros que tienes, los que quieres leer y los que ya has leído. Cada libro que añades es una hoja en tu árbol. Empecemos creando tu primera estantería.'),
('tutorial.chapter_2.heading','tutorial','Vamos adicionar o teu primeiro livro.','Let’s add your first book.','Ajoutons ton premier livre.','Vamos a añadir tu primer libro.'),
('tutorial.chapter_2.body','tutorial','Para adicionar um livro precisamos do ISBN — o número único de identificação do livro. Normalmente encontras-o na contracapa, junto ao código de barras. Tem entre 9 e 13 dígitos. Se vires um livro que queres mas ainda não tens, podes adicioná-lo à Wishlist — voltamos a isso mais tarde.','To add a book we need its ISBN — the unique identification number for the book. You usually find it on the back cover, near the barcode. It has 9 to 13 digits. If you see a book you want but do not own yet, you can add it to your Wishlist — we’ll return to that later.','Pour ajouter un livre, il faut son ISBN — son numéro d’identification unique. Tu le trouves généralement au dos, près du code-barres. Il compte 9 à 13 chiffres. Si tu vois un livre que tu veux mais que tu n’as pas encore, tu peux l’ajouter à ta Wishlist — nous y reviendrons plus tard.','Para añadir un libro necesitamos su ISBN — el número único de identificación del libro. Normalmente está en la contraportada, junto al código de barras. Tiene entre 9 y 13 dígitos. Si ves un libro que quieres pero aún no tienes, puedes añadirlo a tu Wishlist — volveremos a eso más tarde.'),
('tutorial.chapter_3.heading','tutorial','Abre o livro que acabaste de adicionar.','Open the book you just added.','Ouvre le livre que tu viens d’ajouter.','Abre el libro que acabas de añadir.'),
('tutorial.chapter_3.body','tutorial','Toca no livro para ver os seus detalhes. Ali podes editar a informação, indicar se já leste, estás a ler, ou ainda não leste. Podes também escrever notas, citações e os teus pensamentos sobre o livro. E se quiseres partilhá-lo com um colega, podes activar o empréstimo.','Tap the book to see its details. There you can edit information, mark whether you have read it, are reading it, or have not read it yet. You can also write notes, quotes, and your thoughts about the book. And if you want to share it with a classmate, you can enable lending.','Touche le livre pour voir ses détails. Tu peux y modifier les informations, indiquer si tu l’as lu, si tu le lis ou si tu ne l’as pas encore lu. Tu peux aussi écrire des notes, des citations et tes pensées. Et si tu veux le partager avec un camarade, tu peux activer le prêt.','Toca el libro para ver sus detalles. Allí puedes editar la información, indicar si ya lo leíste, lo estás leyendo o aún no lo has leído. También puedes escribir notas, citas y tus pensamientos sobre el libro. Y si quieres compartirlo con un compañero, puedes activar el préstamo.'),
('tutorial.chapter_4.heading','tutorial','Vamos ao teu perfil.','Let’s go to your profile.','Allons à ton profil.','Vamos a tu perfil.'),
('tutorial.chapter_4.body','tutorial','O teu perfil é o teu espaço pessoal. Toca em Perfil para explorarmos juntos.','Your profile is your personal space. Tap Profile so we can explore it together.','Ton profil est ton espace personnel. Touche Profil pour l’explorer ensemble.','Tu perfil es tu espacio personal. Toca Perfil para explorarlo juntos.'),
('tutorial.chapter_5.heading','tutorial','Define a tua escola.','Set your school.','Définis ton école.','Define tu escuela.'),
('tutorial.chapter_5.body','tutorial','Se tens menos de 18 anos, é importante definires a tua escola actual. Isso permite-nos activar as opções de empréstimo entre colegas — podes emprestar livros a alunos da tua escola e distrito, e eles podem emprestar-te a ti.','If you are under 18, it is important to set your current school. This lets us enable lending between classmates — you can lend books to students from your school and district, and they can lend books to you.','Si tu as moins de 18 ans, il est important de définir ton école actuelle. Cela permet d’activer les prêts entre camarades — tu peux prêter des livres aux élèves de ton école et de ton district, et ils peuvent t’en prêter.','Si tienes menos de 18 años, es importante definir tu escuela actual. Esto nos permite activar los préstamos entre compañeros: puedes prestar libros a alumnos de tu escuela y distrito, y ellos pueden prestártelos a ti.'),
('tutorial.chapter_6.heading','tutorial','Há muito mais aqui.','There is much more here.','Il y a beaucoup plus ici.','Hay mucho más aquí.'),
('tutorial.chapter_6.body','tutorial','No perfil podes ver as tuas estatísticas de leitura, os teus livros favoritos e as tuas leituras actuais. Também podes mudar o idioma da app ou escolher um tema diferente — cada tema é inspirado numa aldeia histórica portuguesa.','In your profile you can see your reading stats, favourite books, and current reads. You can also change the app language or choose a different theme — each theme is inspired by a historic Portuguese village.','Dans ton profil, tu peux voir tes statistiques de lecture, tes livres favoris et tes lectures en cours. Tu peux aussi changer la langue de l’app ou choisir un thème différent — chaque thème s’inspire d’un village historique portugais.','En tu perfil puedes ver tus estadísticas de lectura, tus libros favoritos y tus lecturas actuales. También puedes cambiar el idioma de la app o elegir un tema diferente — cada tema está inspirado en una aldea histórica portuguesa.'),
('tutorial.chapter_7.heading','tutorial','Descobre o que está à tua volta.','Discover what is around you.','Découvre ce qui t’entoure.','Descubre lo que te rodea.'),
('tutorial.chapter_7.body','tutorial','No Procurar tens três ferramentas: podes pesquisar livros disponíveis para empréstimo por alunos da tua escola e distrito; podes encontrar bibliotecas públicas perto de ti; e podes descobrir listas de leitura disponibilizadas pelos teus professores ou por entidades nacionais como o Plano Nacional de Leitura.','In Search you have three tools: you can find books available to borrow from students in your school and district; find public libraries near you; and discover reading lists shared by teachers or national entities such as the National Reading Plan.','Dans Rechercher, tu as trois outils : trouver des livres disponibles au prêt par des élèves de ton école et de ton district ; trouver des bibliothèques publiques près de toi ; et découvrir des listes de lecture partagées par tes professeurs ou des organismes nationaux comme le Plan National de Lecture.','En Buscar tienes tres herramientas: puedes encontrar libros disponibles para préstamo por alumnos de tu escuela y distrito; encontrar bibliotecas públicas cercanas; y descubrir listas de lectura compartidas por tus profesores o entidades nacionales como el Plan Nacional de Lectura.'),
('tutorial.chapter_8.heading','tutorial','Os teus planos de leitura.','Your reading plans.','Tes plans de lecture.','Tus planes de lectura.'),
('tutorial.chapter_8.body','tutorial','Em Listas encontras três secções. A Wishlist guarda os livros que queres um dia ler. Em Planos podes criar um plano de leitura mensal — comprometes-te a ler certos livros em certos meses. Em Listas podes criar as tuas próprias listas ou importar listas como o Plano Nacional de Leitura.','In Lists you will find three sections. Wishlist stores the books you want to read one day. In Plans you can create a monthly reading plan — committing to read certain books in certain months. In Lists you can create your own lists or import lists such as the National Reading Plan.','Dans Listes, tu trouveras trois sections. Wishlist garde les livres que tu veux lire un jour. Dans Plans, tu peux créer un plan de lecture mensuel — t’engager à lire certains livres certains mois. Dans Listes, tu peux créer tes propres listes ou importer des listes comme le Plan National de Lecture.','En Listas encontrarás tres secciones. Wishlist guarda los libros que quieres leer algún día. En Planes puedes crear un plan mensual de lectura — comprometiéndote a leer ciertos libros en ciertos meses. En Listas puedes crear tus propias listas o importar listas como el Plan Nacional de Lectura.'),
('tutorial.chapter_9.heading','tutorial','O que se passa à tua volta.','What is happening around you.','Ce qui se passe autour de toi.','Lo que pasa a tu alrededor.'),
('tutorial.chapter_9.body','tutorial','Em Eventos os teus professores e entidades como bibliotecas e o Plano Nacional de Leitura publicam acontecimentos relacionados com leitura — clubes de leitura, concursos de escrita, feiras do livro, conferências, e muito mais. Inscreve-te nos que te interessam e fica a saber quando são.','In Events your teachers and organisations like libraries and the National Reading Plan publish reading-related happenings — book clubs, writing competitions, book fairs, conferences, and more. Register for the ones that interest you and keep track of when they happen.','Dans Événements, tes professeurs et des organismes comme les bibliothèques et le Plan National de Lecture publient des activités liées à la lecture — clubs de lecture, concours d’écriture, salons du livre, conférences et bien plus. Inscris-toi à ceux qui t’intéressent et garde leurs dates.','En Eventos tus profesores y entidades como bibliotecas y el Plan Nacional de Lectura publican actividades relacionadas con la lectura — clubes de lectura, concursos de escritura, ferias del libro, conferencias y mucho más. Inscríbete en las que te interesen y conoce cuándo son.'),
('tutorial.chapter_10.heading','tutorial','A tua estante está plantada.','Your shelf is planted.','Ton étagère est plantée.','Tu estantería está plantada.'),
('tutorial.chapter_10.body','tutorial','Há muito mais para explorar no Folium. Mas por agora, já sabes o essencial: guardar livros, partilhá-los, planear as tuas leituras, e descobrir o que os outros estão a ler. Cada livro que adicionas é uma folha nova. Vai crescendo.','There is much more to explore in Folium. But for now, you know the essentials: saving books, sharing them, planning your reading, and discovering what others are reading. Every book you add is a new leaf. Keep growing.','Il y a encore beaucoup à explorer dans Folium. Mais pour l’instant, tu connais l’essentiel : garder des livres, les partager, planifier tes lectures et découvrir ce que les autres lisent. Chaque livre ajouté est une nouvelle feuille. Continue de grandir.','Hay mucho más por explorar en Folium. Pero por ahora, ya sabes lo esencial: guardar libros, compartirlos, planificar tus lecturas y descubrir lo que otros están leyendo. Cada libro que añades es una hoja nueva. Sigue creciendo.')
ON CONFLICT (key) DO UPDATE SET
category = EXCLUDED.category,
value_pt = EXCLUDED.value_pt,
value_en = EXCLUDED.value_en,
value_fr = EXCLUDED.value_fr,
value_es = EXCLUDED.value_es,
updated_at = now();